kayac-isucon:
  ssh_options:
    user: isucon
    keys: ~/.ssh/isucon.key
    host_name: kayac-isucon-2022
  properties:
    preferred_driver: mitamae
    nopasswd_sudo: true
    attributes:
      users:
        - name: shiimaxx
          authorized_keys: https://github.com/shiimaxx.keys
        - name: nari_ex
          authorized_keys: https://github.com/nari-ex.keys
        - name: kur_neko
          authorized_keys: https://github.com/kurneko.keys
    run_list:
      - isucon.rb
